#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder
  namespace: default
spec:
  serviceAccountName: kpack-service-account
  tag: #@ data.values.kpack.builder.tag
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/dotnet-core 
  - group:
    - id: paketo-buildpacks/dotnet-core-aspnet
  - group:
    - id: paketo-buildpacks/dotnet-publish