#@ load("@ytt:data", "data")

#@ buildpack_versions = {
#@   "dotnet-core": "latest",
#@   "go": "latest",
#@   "java": "latest",
#@   "nodejs": "latest",
#@   "php": "latest",
#@   "ruby": "latest",
#@ }

apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
  - image: gcr.io/paketo-buildpacks/dotnet-core
  - image: gcr.io/paketo-buildpacks/dotnet-core-aspnet
  - image: gcr.io/paketo-buildpacks/dotnet-publish

